name: Jazzy CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-ros-jazzy-ros-base-latest
    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          # use-ros2-testing: true
          required-ros-distributions: jazzy

      - name: Checkout Repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ROS 2 package
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: unitree_ros 
          target-ros2-distro: jazzy

