name: Jazzy CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup ROS2
        uses: ros-tooling/setup-ros@0.7.7
        with:
          use-ros2-testing: true
          required-ros-distributions: jazzy

      - name: Checkout Repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build ROS 2 package
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: unitree_ros 
          target-ros2-distro: jazzy

